# Generated by Django 4.0.4 on 2022-07-15 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('time', models.TimeField()),
                ('price', models.IntegerField(default=0)),
                ('memo', models.TextField(blank=True, null=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_people', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('place', models.CharField(max_length=30)),
                ('date_and_time', models.DateTimeField(verbose_name='hope datetime')),
                ('pub_date_and_time', models.DateTimeField(verbose_name='date published')),
                ('memo', models.TextField(blank=True, null=True)),
                ('customer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_people', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('place', models.CharField(max_length=30)),
                ('date_and_time', models.DateTimeField(verbose_name='suggestion datetime')),
                ('pub_date_and_time', models.DateTimeField(verbose_name='date published')),
                ('memo', models.TextField(blank=True, null=True)),
                ('auto_flag', models.BooleanField(default=0)),
                ('hope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microposts.hope')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microposts.suggestion')),
            ],
        ),
        migrations.CreateModel(
            name='Orderunit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('memo', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='microposts.course')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
