# Generated by Django 4.0.4 on 2022-07-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microposts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderunit',
            name='course',
        ),
        migrations.RemoveField(
            model_name='orderunit',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='suggestion',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='hope',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='shop',
        ),
        migrations.AlterField(
            model_name='hope',
            name='pub_date_and_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterModelTable(
            name='hope',
            table='hopes',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Orderunit',
        ),
        migrations.DeleteModel(
            name='Reserve',
        ),
        migrations.DeleteModel(
            name='Suggestion',
        ),
    ]
